In [1]:
import numpy as np
import pandas as pd
import os

In [3]:
data_dir = '../data/dblp/oriData/'
pa_data = pd.read_csv(os.path.join(data_dir,'paper_author.txt'),header=None,sep='\t')
pa_data

           0      1
0          0   7383
1          0   8503
2          1   2492
3          1  13694
4          1  13149
5          1  14307
6          1   6702
7          2  12246
8          3  12986
9          3     86
10         3   5284
11         3   2448
12         4  12246
13         5  12246
14         6   6696
15         6   8949
16         6   7416
17         6  12699
18         7  14090
19         7   8424
20         7   5040
21         7  12656
22         8   9941
23         8  13308
24         8  10324
25         9   2100
26         9   7700
27        10   1349
28        11  10615
29        11   6442
...      ...    ...
41764  14364   7445
41765  14364    898
41766  14365   2165
41767  14365   7604
41768  14365   8787
41769  14366   3467
41770  14367   6167
41771  14368  12574
41772  14368   2506
41773  14368    854
41774  14368   7182
41775  14368   4206
41776  14369  10992
41777  14369  10991
41778  14369  10988
41779  14370   6822
41780  14370   6821
41781  14371   2396
41782  14372  13273
41783  14372   2396
41784  14373   6092
41785  14373   6820
41786  14373    471
41787  14374  13875
41788  14374   3349
41789  14374  10907
41790  14374   2858
41791  14375   9024
41792  14375   3822
41793  14375   3346

[41794 rows x 2 columns]

In [4]:
pc_data = pd.read_csv(os.path.join(data_dir,'paper_conf.txt'),header=None,sep='\t')
pc_data

           0   1
0          0  14
1          1  17
2          2  10
3          3  10
4          4  10
5          5  10
6          6  10
7          7  17
8          8  13
9          9  18
10        10   5
11        11  18
12        12  18
13        13  18
14        14   5
15        15   8
16        16  14
17        17  14
18        18  14
19        19  14
20        20  14
21        21  18
22        22  18
23        23   2
24        24  18
25        25   2
26        26  18
27        27  12
28        28  12
29        29  14
...      ...  ..
14346  14346   5
14347  14347   5
14348  14348   5
14349  14349  13
14350  14350   7
14351  14351   7
14352  14352  15
14353  14353   5
14354  14354   7
14355  14355   7
14356  14356   7
14357  14357   7
14358  14358   7
14359  14359  14
14360  14360  10
14361  14361  15
14362  14362  15
14363  14363  15
14364  14364   5
14365  14365   4
14366  14366  15
14367  14367  15
14368  14368  15
14369  14369  10
14370  14370  10
14371  14371  10
14372  14372  10
14373  14373  10
14374  14374  17
14375  14375  17

[14376 rows x 2 columns]

In [5]:
len(set(pa_data[0])), len(set(pa_data[1]))

(14376, 14475)

In [7]:
A_pa_data = pa_data.copy()
A_pa_data

           0      1
0          0   7383
1          0   8503
2          1   2492
3          1  13694
4          1  13149
5          1  14307
6          1   6702
7          2  12246
8          3  12986
9          3     86
10         3   5284
11         3   2448
12         4  12246
13         5  12246
14         6   6696
15         6   8949
16         6   7416
17         6  12699
18         7  14090
19         7   8424
20         7   5040
21         7  12656
22         8   9941
23         8  13308
24         8  10324
25         9   2100
26         9   7700
27        10   1349
28        11  10615
29        11   6442
...      ...    ...
41764  14364   7445
41765  14364    898
41766  14365   2165
41767  14365   7604
41768  14365   8787
41769  14366   3467
41770  14367   6167
41771  14368  12574
41772  14368   2506
41773  14368    854
41774  14368   7182
41775  14368   4206
41776  14369  10992
41777  14369  10991
41778  14369  10988
41779  14370   6822
41780  14370   6821
41781  14371   2396
41782  14372  13273
41783  14372   2396
41784  14373   6092
41785  14373   6820
41786  14373    471
41787  14374  13875
41788  14374   3349
41789  14374  10907
41790  14374   2858
41791  14375   9024
41792  14375   3822
41793  14375   3346

[41794 rows x 2 columns]

In [8]:
A_pa_data.iloc[:, 1] = A_pa_data.iloc[:, 1].apply(lambda x:x+14376)

In [18]:
len(np.array(A_pa_data[1]).tolist()+np.array(A_pa_data[0]).tolist())

83588

In [13]:
from scipy.sparse import csr_matrix
n = len(set(A_pa_data[0]))+len(set(A_pa_data[1]))
row = np.array(A_pa_data[0]).tolist()+np.array(A_pa_data[1]).tolist()
col = np.array(A_pa_data[1]).tolist()+np.array(A_pa_data[0]).tolist()
data = np.ones(len(row))
pa_mtx = csr_matrix((data, (row, col)), shape=(n, n))

In [14]:
pa_mtx.shape

(28851, 28851)

In [15]:
import scipy.io
scipy.io.savemat(os.path.join(data_dir,'pa_csr'),{"pa":pa_mtx})

In [63]:
scipy.io.savemat(os.path.join(data_dir,'ap_csr'),{"ap":pa_mtx.transpose()})

In [11]:
A_pc_data = pc_data.copy()
n_p = len(pc_data[0])
A_pc_data.iloc[:, 1] = A_pc_data.iloc[:, 1].apply(lambda x:x+n_p)
n_pc = len(set(A_pc_data[0]))+len(set(A_pc_data[1]))
row = np.array(A_pc_data[0]).tolist()+np.array(A_pc_data[1]).tolist()
col = np.array(A_pc_data[1]).tolist()+np.array(A_pc_data[0]).tolist()
data = np.ones(len(row))
pc_mtx = csr_matrix((data, (row, col)), shape=(n_pc, n_pc))
A_pc_data

           0      1
0          0  14390
1          1  14393
2          2  14386
3          3  14386
4          4  14386
5          5  14386
6          6  14386
7          7  14393
8          8  14389
9          9  14394
10        10  14381
11        11  14394
12        12  14394
13        13  14394
14        14  14381
15        15  14384
16        16  14390
17        17  14390
18        18  14390
19        19  14390
20        20  14390
21        21  14394
22        22  14394
23        23  14378
24        24  14394
25        25  14378
26        26  14394
27        27  14388
28        28  14388
29        29  14390
...      ...    ...
14346  14346  14381
14347  14347  14381
14348  14348  14381
14349  14349  14389
14350  14350  14383
14351  14351  14383
14352  14352  14391
14353  14353  14381
14354  14354  14383
14355  14355  14383
14356  14356  14383
14357  14357  14383
14358  14358  14383
14359  14359  14390
14360  14360  14386
14361  14361  14391
14362  14362  14391
14363  14363  14391
14364  14364  14381
14365  14365  14380
14366  14366  14391
14367  14367  14391
14368  14368  14391
14369  14369  14386
14370  14370  14386
14371  14371  14386
14372  14372  14386
14373  14373  14386
14374  14374  14393
14375  14375  14393

[14376 rows x 2 columns]

In [1]:
np.array(A_pc_data[0]).tolist()

NameError: name 'np' is not defined

In [12]:
scipy.io.savemat(os.path.join(data_dir,'pc_csr'),{"pc":pc_mtx})

In [38]:
# apc csr matrix
apc_data = pd.read_csv(os.path.join(data_dir,'apc.txt'),header=None,sep='\t')
A_apc_data = apc_data.copy()
A_apc_data

           0   1    2
0          0   5  1.0
1          1   3  1.0
2          1  12  1.0
3          1  13  1.0
4          2   3  1.0
5          2  19  1.0
6          3   3  1.0
7          3  19  1.0
8          4  17  1.0
9          5   3  1.0
10         5  11  1.0
11         6   3  1.0
12         7  13  1.0
13         8  18  1.0
14         9   3  1.0
15        10   2  5.0
16        10   3  2.0
17        10   5  4.0
18        10   7  1.0
19        10  15  1.0
20        10  16  1.0
21        11  17  1.0
22        12  10  1.0
23        12  14  4.0
24        13   3  1.0
25        13  10  2.0
26        13  12  1.0
27        14  10  1.0
28        15  10  1.0
29        16  10  2.0
...      ...  ..  ...
24465  14461   6  1.0
24466  14461   8  2.0
24467  14461  15  1.0
24468  14462  14  1.0
24469  14463   2  1.0
24470  14463   5  2.0
24471  14464   1  1.0
24472  14464   2  4.0
24473  14464   3  2.0
24474  14464   7  2.0
24475  14464   8  1.0
24476  14464  15  2.0
24477  14464  16  1.0
24478  14465   7  1.0
24479  14465  15  1.0
24480  14466   5  1.0
24481  14467   4  1.0
24482  14467  12  1.0
24483  14468   2  2.0
24484  14468   5  1.0
24485  14469  14  1.0
24486  14470   9  1.0
24487  14470  14  1.0
24488  14470  18  3.0
24489  14471   3  1.0
24490  14472  15  1.0
24491  14473   0  1.0
24492  14473   2  2.0
24493  14473  15  2.0
24494  14474  14  1.0

[24495 rows x 3 columns]

In [39]:
n_a = len(set(pa_data[1]))
A_apc_data.iloc[:, 1] = A_apc_data.iloc[:, 1].apply(lambda x:x+n_a)
A_apc_data

           0      1    2
0          0  14480  1.0
1          1  14478  1.0
2          1  14487  1.0
3          1  14488  1.0
4          2  14478  1.0
5          2  14494  1.0
6          3  14478  1.0
7          3  14494  1.0
8          4  14492  1.0
9          5  14478  1.0
10         5  14486  1.0
11         6  14478  1.0
12         7  14488  1.0
13         8  14493  1.0
14         9  14478  1.0
15        10  14477  5.0
16        10  14478  2.0
17        10  14480  4.0
18        10  14482  1.0
19        10  14490  1.0
20        10  14491  1.0
21        11  14492  1.0
22        12  14485  1.0
23        12  14489  4.0
24        13  14478  1.0
25        13  14485  2.0
26        13  14487  1.0
27        14  14485  1.0
28        15  14485  1.0
29        16  14485  2.0
...      ...    ...  ...
24465  14461  14481  1.0
24466  14461  14483  2.0
24467  14461  14490  1.0
24468  14462  14489  1.0
24469  14463  14477  1.0
24470  14463  14480  2.0
24471  14464  14476  1.0
24472  14464  14477  4.0
24473  14464  14478  2.0
24474  14464  14482  2.0
24475  14464  14483  1.0
24476  14464  14490  2.0
24477  14464  14491  1.0
24478  14465  14482  1.0
24479  14465  14490  1.0
24480  14466  14480  1.0
24481  14467  14479  1.0
24482  14467  14487  1.0
24483  14468  14477  2.0
24484  14468  14480  1.0
24485  14469  14489  1.0
24486  14470  14484  1.0
24487  14470  14489  1.0
24488  14470  14493  3.0
24489  14471  14478  1.0
24490  14472  14490  1.0
24491  14473  14475  1.0
24492  14473  14477  2.0
24493  14473  14490  2.0
24494  14474  14489  1.0

[24495 rows x 3 columns]

In [40]:
A_apc_data[2]

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
5        1.0
6        1.0
7        1.0
8        1.0
9        1.0
10       1.0
11       1.0
12       1.0
13       1.0
14       1.0
15       5.0
16       2.0
17       4.0
18       1.0
19       1.0
20       1.0
21       1.0
22       1.0
23       4.0
24       1.0
25       2.0
26       1.0
27       1.0
28       1.0
29       2.0
        ...
24465    1.0
24466    2.0
24467    1.0
24468    1.0
24469    1.0
24470    2.0
24471    1.0
24472    4.0
24473    2.0
24474    2.0
24475    1.0
24476    2.0
24477    1.0
24478    1.0
24479    1.0
24480    1.0
24481    1.0
24482    1.0
24483    2.0
24484    1.0
24485    1.0
24486    1.0
24487    1.0
24488    3.0
24489    1.0
24490    1.0
24491    1.0
24492    2.0
24493    2.0
24494    1.0
Name: 2, Length: 24495, dtype: float64

In [41]:
n_apc = len(set(A_apc_data[0]))+len(set(A_apc_data[1]))
row = np.array(A_apc_data[0]).tolist()+np.array(A_apc_data[1]).tolist()
col = np.array(A_apc_data[1]).tolist()+np.array(A_apc_data[0]).tolist()
data = A_apc_data[2].tolist()+A_apc_data[2].tolist()
apc_mtx = csr_matrix((data, (row, col)), shape=(n_apc, n_apc))
np.nonzero(apc_mtx)

(array([    0,     1,     1, ..., 14494, 14494, 14494], dtype=int32),
 array([14480, 14478, 14487, ..., 13875, 13905, 14357], dtype=int32))

In [42]:
scipy.io.savemat(os.path.join(data_dir,'apc_csr'),{"apc":apc_mtx})

In [43]:
# apt csr matrix
apt_data = pd.read_csv(os.path.join(data_dir,'apt.txt'),header=None,sep='\t')
A_apt_data = apt_data.copy()
A_apt_data

            0     1    2
0           0  1964  1.0
1           0  2174  1.0
2           0  2274  1.0
3           0  3507  1.0
4           0  5451  1.0
5           0  5858  1.0
6           0  6552  1.0
7           1   597  1.0
8           1   712  1.0
9           1   853  1.0
10          1   912  1.0
11          1  1160  1.0
12          1  2232  1.0
13          1  2274  1.0
14          1  2865  1.0
15          1  3486  1.0
16          1  4318  1.0
17          1  6231  1.0
18          1  6566  1.0
19          1  6824  1.0
20          1  7053  1.0
21          1  7439  1.0
22          1  7818  1.0
23          1  8453  1.0
24          1  8688  1.0
25          2  1160  1.0
26          2  2232  2.0
27          2  2511  1.0
28          2  3486  1.0
29          2  4318  1.0
...       ...   ...  ...
217108  14472  5301  1.0
217109  14473    73  1.0
217110  14473   526  1.0
217111  14473   614  1.0
217112  14473   805  1.0
217113  14473   900  1.0
217114  14473  1060  2.0
217115  14473  2828  1.0
217116  14473  2851  1.0
217117  14473  3336  1.0
217118  14473  3486  1.0
217119  14473  3834  1.0
217120  14473  4079  1.0
217121  14473  4701  1.0
217122  14473  5232  1.0
217123  14473  5675  1.0
217124  14473  6050  1.0
217125  14473  6215  2.0
217126  14473  6387  1.0
217127  14473  6566  1.0
217128  14473  6736  1.0
217129  14473  6828  3.0
217130  14473  6906  1.0
217131  14473  7493  1.0
217132  14473  8465  1.0
217133  14473  8721  1.0
217134  14474  2518  1.0
217135  14474  4549  1.0
217136  14474  4961  1.0
217137  14474  8423  1.0

[217138 rows x 3 columns]

In [44]:
n_a = len(set(pa_data[1]))
A_apt_data.iloc[:, 1] = A_apt_data.iloc[:, 1].apply(lambda x:x+n_a)
A_apt_data

            0      1    2
0           0  16439  1.0
1           0  16649  1.0
2           0  16749  1.0
3           0  17982  1.0
4           0  19926  1.0
5           0  20333  1.0
6           0  21027  1.0
7           1  15072  1.0
8           1  15187  1.0
9           1  15328  1.0
10          1  15387  1.0
11          1  15635  1.0
12          1  16707  1.0
13          1  16749  1.0
14          1  17340  1.0
15          1  17961  1.0
16          1  18793  1.0
17          1  20706  1.0
18          1  21041  1.0
19          1  21299  1.0
20          1  21528  1.0
21          1  21914  1.0
22          1  22293  1.0
23          1  22928  1.0
24          1  23163  1.0
25          2  15635  1.0
26          2  16707  2.0
27          2  16986  1.0
28          2  17961  1.0
29          2  18793  1.0
...       ...    ...  ...
217108  14472  19776  1.0
217109  14473  14548  1.0
217110  14473  15001  1.0
217111  14473  15089  1.0
217112  14473  15280  1.0
217113  14473  15375  1.0
217114  14473  15535  2.0
217115  14473  17303  1.0
217116  14473  17326  1.0
217117  14473  17811  1.0
217118  14473  17961  1.0
217119  14473  18309  1.0
217120  14473  18554  1.0
217121  14473  19176  1.0
217122  14473  19707  1.0
217123  14473  20150  1.0
217124  14473  20525  1.0
217125  14473  20690  2.0
217126  14473  20862  1.0
217127  14473  21041  1.0
217128  14473  21211  1.0
217129  14473  21303  3.0
217130  14473  21381  1.0
217131  14473  21968  1.0
217132  14473  22940  1.0
217133  14473  23196  1.0
217134  14474  16993  1.0
217135  14474  19024  1.0
217136  14474  19436  1.0
217137  14474  22898  1.0

[217138 rows x 3 columns]

In [45]:
n_apt = len(set(A_apt_data[0]))+len(set(A_apt_data[1]))
row = np.array(A_apt_data[0]).tolist()+np.array(A_apt_data[1]).tolist()
col = np.array(A_apt_data[1]).tolist()+np.array(A_apt_data[0]).tolist()
data = A_apt_data[2].tolist()+A_apt_data[2].tolist()
apt_mtx = csr_matrix((data, (row, col)), shape=(n_apt, n_apt))
np.nonzero(apt_mtx)

(array([    0,     0,     0, ..., 23284, 23284, 23285], dtype=int32),
 array([16439, 16649, 16749, ...,  4723, 12793, 11545], dtype=int32))

In [46]:
scipy.io.savemat(os.path.join(data_dir,'apt_csr'),{"apt":apt_mtx})

In [47]:
# apa csr matrx
apa_data = pd.read_csv(os.path.join(data_dir,'apa.txt'),header=None,sep='\t')
A_apa_data = apa_data.copy()
A_apa_data

           0      1    2
0          0      0  1.0
1          0   4793  1.0
2          0   7309  1.0
3          1      1  3.0
4          1      2  1.0
5          1      3  1.0
6          1    782  1.0
7          1   1856  1.0
8          1   1861  1.0
9          1   6813  1.0
10         1   9083  2.0
11         1   9084  1.0
12         1   9086  1.0
13         1  11635  1.0
14         1  13496  1.0
15         2      1  1.0
16         2      2  2.0
17         2      3  2.0
18         2    515  1.0
19         2    618  1.0
20         2   1861  1.0
21         2   6659  1.0
22         2   9070  1.0
23         2   9086  2.0
24         2  10236  1.0
25         2  10292  1.0
26         2  11635  1.0
27         2  13238  1.0
28         3      1  1.0
29         3      2  2.0
...      ...    ...  ...
94983  14469   8588  1.0
94984  14469  14469  1.0
94985  14470   1399  1.0
94986  14470   1417  1.0
94987  14470   2999  1.0
94988  14470   5803  1.0
94989  14470   5969  1.0
94990  14470  10743  5.0
94991  14470  14470  5.0
94992  14471   6005  1.0
94993  14471  11972  1.0
94994  14471  14471  1.0
94995  14472    397  1.0
94996  14472   2864  1.0
94997  14472   5028  1.0
94998  14472   5053  1.0
94999  14472   8535  1.0
95000  14472   9374  1.0
95001  14472   9375  1.0
95002  14472  10078  1.0
95003  14472  10921  1.0
95004  14472  12649  1.0
95005  14472  14472  1.0
95006  14473  11458  5.0
95007  14473  12919  1.0
95008  14473  14473  5.0
95009  14474   1644  1.0
95010  14474   5655  1.0
95011  14474   9584  1.0
95012  14474  14474  1.0

[95013 rows x 3 columns]

In [53]:
len(set(A_apa_data[0]))

14475

In [55]:
n_apa = len(set(A_apa_data[0]))
row = np.array(A_apa_data[0]).tolist()
col = np.array(A_apa_data[1]).tolist()
data = A_apa_data[2].tolist()
apa_mtx = csr_matrix((data, (row, col)), shape=(n_apa, n_apa))
np.nonzero(apa_mtx)

(array([    0,     0,     0, ..., 14474, 14474, 14474], dtype=int32),
 array([    0,  4793,  7309, ...,  5655,  9584, 14474], dtype=int32))

In [56]:
scipy.io.savemat(os.path.join(data_dir,'apa_csr'),{"apa":apa_mtx})

In [57]:
# apcpa csr matrx
apcpa_data = pd.read_csv(os.path.join(data_dir,'apcpa.txt'),header=None,sep='\t')
A_apcpa_data = apcpa_data.copy()
A_apcpa_data

              0      1    2
0             0      0  1.0
1             0     10  4.0
2             0     20  1.0
3             0     25  1.0
4             0     37  2.0
5             0     46  1.0
6             0     69  1.0
7             0     91  3.0
8             0     95  1.0
9             0     97  7.0
10            0     98  4.0
11            0    102  2.0
12            0    103  1.0
13            0    104  1.0
14            0    113  1.0
15            0    121  2.0
16            0    123  1.0
17            0    124  3.0
18            0    126  4.0
19            0    127  1.0
20            0    128  1.0
21            0    129  1.0
22            0    131  2.0
23            0    148  1.0
24            0    151  2.0
25            0    152  3.0
26            0    154  1.0
27            0    160  1.0
28            0    161  1.0
29            0    177  1.0
...         ...    ...  ...
38905143  14474  14286  1.0
38905144  14474  14289  1.0
38905145  14474  14302  1.0
38905146  14474  14318  1.0
38905147  14474  14324  1.0
38905148  14474  14325  1.0
38905149  14474  14328  1.0
38905150  14474  14336  1.0
38905151  14474  14342  1.0
38905152  14474  14349  1.0
38905153  14474  14351  2.0
38905154  14474  14362  1.0
38905155  14474  14363  1.0
38905156  14474  14365  1.0
38905157  14474  14366  4.0
38905158  14474  14367  1.0
38905159  14474  14368  1.0
38905160  14474  14369  2.0
38905161  14474  14394  1.0
38905162  14474  14399  1.0
38905163  14474  14406  1.0
38905164  14474  14409  1.0
38905165  14474  14413  2.0
38905166  14474  14425  1.0
38905167  14474  14427  1.0
38905168  14474  14443  1.0
38905169  14474  14462  1.0
38905170  14474  14469  1.0
38905171  14474  14470  1.0
38905172  14474  14474  1.0

[38905173 rows x 3 columns]

In [58]:
n_apcpa = len(set(A_apcpa_data[0]))
row = np.array(A_apcpa_data[0]).tolist()
col = np.array(A_apcpa_data[1]).tolist()
data = A_apcpa_data[2].tolist()
apcpa_mtx = csr_matrix((data, (row, col)), shape=(n_apcpa, n_apcpa))
np.nonzero(apcpa_mtx)

(array([    0,     0,     0, ..., 14474, 14474, 14474], dtype=int32),
 array([    0,    10,    20, ..., 14469, 14470, 14474], dtype=int32))

In [59]:
scipy.io.savemat(os.path.join(data_dir,'apcpa_csr'),{"apcpa":apcpa_mtx})

In [60]:
# aptpa csr matrx
aptpa_data = pd.read_csv(os.path.join(data_dir,'aptpa.txt'),header=None,sep='\t')
A_aptpa_data = aptpa_data.copy()
A_aptpa_data

              0      1     2
0             0      0   7.0
1             0      1   1.0
2             0     10   1.0
3             0     20   1.0
4             0     24   3.0
5             0     25   1.0
6             0     26   1.0
7             0     37   1.0
8             0     43   1.0
9             0     50   1.0
10            0     51   1.0
11            0     52   1.0
12            0     53   1.0
13            0     56   1.0
14            0     57   1.0
15            0     61   2.0
16            0     70   3.0
17            0     79   1.0
18            0     80   2.0
19            0     83   1.0
20            0     84  11.0
21            0     86   5.0
22            0     91   8.0
23            0     94   1.0
24            0     97   1.0
25            0     98   1.0
26            0    101   1.0
27            0    102   1.0
28            0    104   2.0
29            0    110   1.0
...         ...    ...   ...
52610797  14474  14162   2.0
52610798  14474  14164   1.0
52610799  14474  14171   1.0
52610800  14474  14206   1.0
52610801  14474  14210   1.0
52610802  14474  14211   1.0
52610803  14474  14222   1.0
52610804  14474  14228   1.0
52610805  14474  14230   1.0
52610806  14474  14237   1.0
52610807  14474  14244   1.0
52610808  14474  14249   1.0
52610809  14474  14253   1.0
52610810  14474  14254   1.0
52610811  14474  14271   1.0
52610812  14474  14298   1.0
52610813  14474  14315   4.0
52610814  14474  14337   1.0
52610815  14474  14382   1.0
52610816  14474  14394   2.0
52610817  14474  14401   1.0
52610818  14474  14404   1.0
52610819  14474  14413   1.0
52610820  14474  14422   1.0
52610821  14474  14429   1.0
52610822  14474  14432   1.0
52610823  14474  14451   1.0
52610824  14474  14464   2.0
52610825  14474  14470   1.0
52610826  14474  14474   4.0

[52610827 rows x 3 columns]

In [61]:
n_aptpa = len(set(A_aptpa_data[0]))
row = np.array(A_aptpa_data[0]).tolist()
col = np.array(A_aptpa_data[1]).tolist()
data = A_aptpa_data[2].tolist()
aptpa_mtx = csr_matrix((data, (row, col)), shape=(n_aptpa, n_aptpa))
np.nonzero(aptpa_mtx)

(array([    0,     0,     0, ..., 14474, 14474, 14474], dtype=int32),
 array([    0,     1,    10, ..., 14464, 14470, 14474], dtype=int32))

In [62]:
scipy.io.savemat(os.path.join(data_dir,'aptpa_csr'),{"aptpa":aptpa_mtx})