In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
data_dir = '../data/dblp'
pa_data = pd.read_csv(os.path.join(data_dir,'paper_author.txt'),header=None,sep='\t')
pa_data

           0      1
0          0   7383
1          0   8503
2          1   2492
3          1  13694
4          1  13149
5          1  14307
6          1   6702
7          2  12246
8          3  12986
9          3     86
10         3   5284
11         3   2448
12         4  12246
13         5  12246
14         6   6696
15         6   8949
16         6   7416
17         6  12699
18         7  14090
19         7   8424
20         7   5040
21         7  12656
22         8   9941
23         8  13308
24         8  10324
25         9   2100
26         9   7700
27        10   1349
28        11  10615
29        11   6442
...      ...    ...
41764  14364   7445
41765  14364    898
41766  14365   2165
41767  14365   7604
41768  14365   8787
41769  14366   3467
41770  14367   6167
41771  14368  12574
41772  14368   2506
41773  14368    854
41774  14368   7182
41775  14368   4206
41776  14369  10992
41777  14369  10991
41778  14369  10988
41779  14370   6822
41780  14370   6821
41781  14371   2396
41782  14372  13273
41783  14372   2396
41784  14373   6092
41785  14373   6820
41786  14373    471
41787  14374  13875
41788  14374   3349
41789  14374  10907
41790  14374   2858
41791  14375   9024
41792  14375   3822
41793  14375   3346

[41794 rows x 2 columns]

In [3]:
pc_data = pd.read_csv(os.path.join(data_dir,'paper_conf.txt'),header=None,sep='\t')
pc_data

           0   1
0          0  14
1          1  17
2          2  10
3          3  10
4          4  10
5          5  10
6          6  10
7          7  17
8          8  13
9          9  18
10        10   5
11        11  18
12        12  18
13        13  18
14        14   5
15        15   8
16        16  14
17        17  14
18        18  14
19        19  14
20        20  14
21        21  18
22        22  18
23        23   2
24        24  18
25        25   2
26        26  18
27        27  12
28        28  12
29        29  14
...      ...  ..
14346  14346   5
14347  14347   5
14348  14348   5
14349  14349  13
14350  14350   7
14351  14351   7
14352  14352  15
14353  14353   5
14354  14354   7
14355  14355   7
14356  14356   7
14357  14357   7
14358  14358   7
14359  14359  14
14360  14360  10
14361  14361  15
14362  14362  15
14363  14363  15
14364  14364   5
14365  14365   4
14366  14366  15
14367  14367  15
14368  14368  15
14369  14369  10
14370  14370  10
14371  14371  10
14372  14372  10
14373  14373  10
14374  14374  17
14375  14375  17

[14376 rows x 2 columns]

In [4]:
len(set(pa_data[0])), len(set(pa_data[1]))

(14376, 14475)

In [5]:
A_pa_data = pa_data.copy()
A_pa_data

           0      1
0          0   7383
1          0   8503
2          1   2492
3          1  13694
4          1  13149
5          1  14307
6          1   6702
7          2  12246
8          3  12986
9          3     86
10         3   5284
11         3   2448
12         4  12246
13         5  12246
14         6   6696
15         6   8949
16         6   7416
17         6  12699
18         7  14090
19         7   8424
20         7   5040
21         7  12656
22         8   9941
23         8  13308
24         8  10324
25         9   2100
26         9   7700
27        10   1349
28        11  10615
29        11   6442
...      ...    ...
41764  14364   7445
41765  14364    898
41766  14365   2165
41767  14365   7604
41768  14365   8787
41769  14366   3467
41770  14367   6167
41771  14368  12574
41772  14368   2506
41773  14368    854
41774  14368   7182
41775  14368   4206
41776  14369  10992
41777  14369  10991
41778  14369  10988
41779  14370   6822
41780  14370   6821
41781  14371   2396
41782  14372  13273
41783  14372   2396
41784  14373   6092
41785  14373   6820
41786  14373    471
41787  14374  13875
41788  14374   3349
41789  14374  10907
41790  14374   2858
41791  14375   9024
41792  14375   3822
41793  14375   3346

[41794 rows x 2 columns]

In [6]:
A_pa_data.iloc[:, 1] = A_pa_data.iloc[:, 1].apply(lambda x:x+14376)

In [40]:
np.array(A_pa_data[1]).tolist()+np.array(A_pa_data[0]).tolist()

[21759,
 22879,
 16868,
 28070,
 27525,
 28683,
 21078,
 26622,
 27362,
 14462,
 19660,
 16824,
 26622,
 26622,
 21072,
 23325,
 21792,
 27075,
 28466,
 22800,
 19416,
 27032,
 24317,
 27684,
 24700,
 16476,
 22076,
 15725,
 24991,
 20818,
 21220,
 21221,
 22076,
 24027,
 18458,
 16835,
 14956,
 26240,
 16416,
 25466,
 27159,
 16416,
 25466,
 20134,
 20288,
 27198,
 22964,
 20317,
 14942,
 27597,
 19745,
 27597,
 19745,
 17803,
 21936,
 24322,
 22670,
 16798,
 21549,
 27603,
 25761,
 20085,
 20468,
 14847,
 19166,
 25216,
 14600,
 14885,
 25951,
 23884,
 16394,
 20896,
 27604,
 28306,
 16576,
 20779,
 18847,
 23429,
 21019,
 26296,
 25953,
 24303,
 24734,
 24584,
 15311,
 19193,
 24958,
 18416,
 15607,
 14462,
 23144,
 15122,
 22344,
 19152,
 19151,
 26120,
 27436,
 27435,
 17590,
 21058,
 19193,
 24958,
 26602,
 27148,
 26481,
 15806,
 16680,
 19457,
 20035,
 16541,
 16638,
 28772,
 28771,
 18421,
 26491,
 25793,
 18459,
 15740,
 15718,
 21107,
 21106,
 26767,
 28730,
 24095,
 24093,
 18117,
 19520,
 28707,
 21073,
 25146,
 21838,
 28712,
 21837,
 26181,
 18405,
 28711,
 28710,
 28709,
 28708,
 25864,
 18378,
 21833,
 20053,
 16188,
 21832,
 18963,
 23009,
 21835,
 21836,
 20165,
 17139,
 21834,
 22732,
 20870,
 20867,
 14854,
 22026,
 16444,
 25477,
 14655,
 15553,
 16195,
 24548,
 15136,
 18082,
 24873,
 15981,
 24294,
 15885,
 14557,
 17872,
 22147,
 22146,
 15385,
 14699,
 23732,
 17376,
 18302,
 17559,
 17549,
 17550,
 17188,
 27647,
 22876,
 15934,
 15933,
 26323,
 18223,
 15787,
 18303,
 23731,
 26853,
 26853,
 16471,
 17364,
 27374,
 23041,
 17352,
 16676,
 23396,
 17315,
 15991,
 27232,
 21556,
 15312,
 16805,
 26430,
 28037,
 23612,
 18975,
 18992,
 23921,
 26782,
 16977,
 23837,
 26958,
 18975,
 27246,
 21547,
 21571,
 25326,
 27839,
 27435,
 14386,
 22808,
 15802,
 24382,
 17331,
 28581,
 26423,
 26426,
 22241,
 22326,
 22325,
 23640,
 24627,
 23041,
 16643,
 16676,
 15698,
 22616,
 24191,
 20197,
 15348,
 16063,
 14684,
 15697,
 15696,
 19480,
 14404,
 21848,
 19888,
 18560,
 20172,
 23779,
 19720,
 19480,
 28340,
 26212,
 19480,
 28340,
 21347,
 17978,
 22461,
 28493,
 26023,
 23508,
 26179,
 15290,
 22849,
 17049,
 15282,
 17480,
 17050,
 17053,
 17054,
 27778,
 15230,
 21475,
 15282,
 15984,
 28323,
 15512,
 18681,
 28106,
 18483,
 17936,
 23712,
 24475,
 16805,
 26599,
 22602,
 26598,
 28288,
 17077,
 26413,
 26606,
 22110,
 26712,
 17351,
 27819,
 25079,
 21484,
 14399,
 19149,
 28093,
 27254,
 25859,
 26540,
 16591,
 22436,
 21963,
 16509,
 24436,
 15406,
 14673,
 24569,
 23394,
 21302,
 17514,
 26713,
 14899,
 23395,
 24235,
 14781,
 14446,
 24474,
 20830,
 21355,
 24471,
 16839,
 17339,
 24390,
 17935,
 16572,
 19521,
 25965,
 18988,
 25870,
 25266,
 25270,
 24446,
 24445,
 24447,
 18555,
 15213,
 22789,
 27217,
 16609,
 24476,
 16798,
 24700,
 20279,
 14958,
 23870,
 24473,
 19628,
 16616,
 16611,
 23740,
 20831,
 23219,
 21475,
 21820,
 20055,
 17411,
 16769,
 24244,
 21475,
 19737,
 23348,
 23350,
 28070,
 21631,
 24214,
 14616,
 22432,
 17063,
 15406,
 25788,
 16854,
 16250,
 25946,
 20580,
 25562,
 24051,
 24571,
 24694,
 24693,
 23011,
 23499,
 27436,
 26065,
 24694,
 24693,
 20666,
 20665,
 27514,
 18425,
 26067,
 23511,
 23512,
 28440,
 25637,
 14929,
 23207,
 18605,
 25672,
 26458,
 24337,
 15984,
 19416,
 28201,
 20968,
 17878,
 27698,
 15562,
 15563,
 15564,
 17736,
 25617,
 19737,
 19146,
 19143,
 23042,
 20543,
 18459,
 27567,
 14615,
 14614,
 27012,
 27763,
 17803,
 18494,
 24518,
 26610,
 14973,
 23351,
 21654,
 20543,
 23095,
 24615,
 17412,
 24975,
 20867,
 15218,
 15782,
 18483,
 16886,
 17936,
 27399,
 22169,
 17669,
 17313,
 20004,
 26595,
 18851,
 16167,
 24440,
 25660,
 16171,
 19044,
 19608,
 24991,
 16999,
 20867,
 18228,
 15792,
 26837,
 15340,
 27070,
 27617,
 21889,
 23155,
 15566,
 23659,
 16059,
 18422,
 26107,
 17964,
 26461,
 22025,
 27054,
 22348,
 24507,
 24289,
 16716,
 16835,
 15808,
 14486,
 25953,
 21344,
 20600,
 17000,
 20059,
 16619,
 19783,
 22585,
 17540,
 28267,
 21714,
 21721,
 27435,
 17281,
 24068,
 23351,
 24300,
 18916,
 18838,
 28079,
 26288,
 16731,
 14654,
 19729,
 27509,
 21630,
 27949,
 27203,
 17662,
 17661,
 22633,
 25870,
 19511,
 25266,
 15750,
 15751,
 16041,
 27907,
 28373,
 18676,
 28062,
 28566,
 16960,
 17401,
 16283,
 27436,
 27435,
 22486,
 14990,
 22386,
 20921,
 22969,
 23511,
 23512,
 21050,
 18671,
 25870,
 18049,
 27108,
 14863,
 20973,
 20974,
 28466,
 19416,
 14997,
 20889,
 21631,
 15050,
 24726,
 24727,
 17615,
 20042,
 18087,
 18088,
 18089,
 17614,
 17613,
 21248,
 28260,
 25206,
 20163,
 21032,
 20376,
 22386,
 20967,
 20034,
 21523,
 27839,
 26013,
 21248,
 21248,
 21867,
 21723,
 21624,
 23011,
 15686,
 26129,
 18543,
 23678,
 25798,
 14774,
 16371,
 28059,
 28678,
 16371,
 28059,
 26759,
 26319,
 27402,
 19497,
 14438,
 27192,
 28726,
 20820,
 27491,
 19232,
 22747,
 25789,
 15738,
 15718,
 17971,
 21722,
 15622,
 18690,
 15686,
 27342,
 21868,
 26394,
 17034,
 26419,
 26418,
 14819,
 23626,
 19559,
 19627,
 19631,
 19630,
 22365,
 22364,
 23400,
 27575,
 27576,
 27577,
 15894,
 15347,
 19631,
 18126,
 20815,
 19102,
 25126,
 20722,
 21539,
 20815,
 27690,
 20815,
 15808,
 22363,
 22362,
 16024,
 20886,
 24333,
 22119,
 18115,
 28361,
 18123,
 22711,
 22176,
 28133,
 21319,
 24333,
 28181,
 15984,
 28201,
 20968,
 20971,
 18002,
 23071,
 22234,
 24842,
 16233,
 19566,
 24503,
 15316,
 27401,
 21577,
 27273,
 15458,
 26597,
 18130,
 22811,
 25352,
 20831,
 18568,
 19816,
 23802,
 24319,
 21805,
 15429,
 15428,
 15423,
 15422,
 18369,
 15425,
 15431,
 23802,
 19711,
 19712,
 23802,
 24601,
 24602,
 15427,
 15426,
 15431,
 27400,
 21820,
 26424,
 22527,
 20333,
 20334,
 15889,
 26958,
 18975,
 25622,
 21572,
 27416,
 19352,
 20328,
 22667,
 24300,
 22081,
 15522,
 25603,
 26506,
 26509,
 28835,
 19766,
 26847,
 16248,
 14836,
 24340,
 23061,
 15819,
 23548,
 27460,
 25955,
 18311,
 17388,
 15819,
 23548,
 16079,
 15049,
 15819,
 20598,
 18127,
 25792,
 28282,
 27996,
 27989,
 27542,
 27984,
 25132,
 25133,
 22285,
 18125,
 18128,
 15340,
 15341,
 18369,
 20964,
 20346,
 16497,
 17560,
 15596,
 27514,
 17255,
 17682,
 24362,
 19665,
 20879,
 20892,
 15808,
 26269,
 20168,
 20506,
 26676,
 22580,
 19884,
 24409,
 18603,
 19604,
 15379,
 18218,
 28546,
 24327,
 24892,
 27850,
 17803,
 14616,
 25533,
 16211,
 22605,
 21627,
 27292,
 23899,
 26958,
 21902,
 18975,
 22037,
 21627,
 27292,
 21023,
 28764,
 24295,
 14529,
 23670,
 27789,
 16726,
 16143,
 23147,
 28440,
 23639,
 18658,
 18343,
 28764,
 15237,
 15984,
 20968,
 26723,
 14547,
 15984,
 15164,
 20997,
 19502,
 27028,
 26102,
 15984,
 15164,
 20997,
 18343,
 28764,
 16041,
 20133,
 19167,
 23953,
 14518,
 20133,
 19167,
 25000,
 17364,
 27778,
 22578,
 20041,
 23026,
 26048,
 20133,
 19167,
 21098,
 15352,
 24711,
 20342,
 26603,
 22460,
 27778,
 22578,
 27059,
 14742,
 24332,
 23979,
 24242,
 25834,
 15353,
 15356,
 15355,
 16197,
 15354,
 27778,
 17325,
 18683,
 15311,
 26555,
 19189,
 28842,
 28812,
 19162,
 20710,
 20277,
 23533,
 20089,
 16662,
 20685,
 21219,
 27910,
 22800,
 26392,
 18810,
 18811,
 27910,
 15972,
 26647,
 18057,
 22516,
 28319,
 22726,
 26875,
 20923,
 24880,
 19789,
 15981,
 26943,
 27162,
 27534,
 27514,
 22211,
 15637,
 22841,
 25464,
 26285,
 17504,
 17940,
 23134,
 21624,
 23792,
 28466,
 22277,
 23792,
 28608,
 20219,
 27514,
 18425,
 26067,
 28165,
 19605,
 26500,
 28335,
 19568,
 19870,
 28004,
 18288,
 24271,
 24331,
 19685,
 19397,
 28073,
 17954,
 18445,
 18444,
 18174,
 23963,
 25737,
 25736,
 17706,
 19019,
 18561,
 25068,
 21646,
 23460,
 25720,
 21707,
 19017,
 19605,
 26500,
 16009,
 17638,
 20598,
 25785,
 21761,
 20291,
 28485,
 19220,
 24629,
 28484,
 24607,
 18290,
 26274,
 18174,
 18572,
 24881,
 19235,
 17621,
 16375,
 21691,
 28735,
 20543,
 26884,
 14469,
 14470,
 22644,
 22037,
 24063,
 27416,
 27406,
 23220,
 23219,
 21396,
 19011,
 26871,
 24532,
 16051,
 23960,
 16887,
 24966,
 17670,
 19240,
 21734,
 24212,
 24211,
 27416,
 19005,
 27406,
 23219,
 ...]

In [41]:
from scipy.sparse import csr_matrix
n = len(set(A_pa_data[0]))+len(set(A_pa_data[1]))
row = np.array(A_pa_data[0]).tolist()+np.array(A_pa_data[1]).tolist()
col = np.array(A_pa_data[1]).tolist()+np.array(A_pa_data[0]).tolist()
data = np.ones(len(row))
pa_mtx = csr_matrix((data, (row, col)), shape=(n, n))

In [42]:
pa_mtx.shape

(28851, 28851)

In [43]:
import scipy.io
scipy.io.savemat(os.path.join(data_dir,'pa'),{"pa":pa_mtx})

In [44]:
A_pc_data = pc_data.copy()
n_p = len(pc_data[0])
A_pc_data.iloc[:, 1] = A_pc_data.iloc[:, 1].apply(lambda x:x+n_p)
n_pc = len(set(A_pc_data[0]))+len(set(A_pc_data[1]))
row = np.array(A_pc_data[0]).tolist()+np.array(A_pc_data[1]).tolist()
col = np.array(A_pc_data[1]).tolist()+np.array(A_pc_data[0]).tolist()
data = np.ones(len(row))
pc_mtx = csr_matrix((data, (row, col)), shape=(n_pc, n_pc))
A_pc_data

           0      1
0          0  14390
1          1  14393
2          2  14386
3          3  14386
4          4  14386
5          5  14386
6          6  14386
7          7  14393
8          8  14389
9          9  14394
10        10  14381
11        11  14394
12        12  14394
13        13  14394
14        14  14381
15        15  14384
16        16  14390
17        17  14390
18        18  14390
19        19  14390
20        20  14390
21        21  14394
22        22  14394
23        23  14378
24        24  14394
25        25  14378
26        26  14394
27        27  14388
28        28  14388
29        29  14390
...      ...    ...
14346  14346  14381
14347  14347  14381
14348  14348  14381
14349  14349  14389
14350  14350  14383
14351  14351  14383
14352  14352  14391
14353  14353  14381
14354  14354  14383
14355  14355  14383
14356  14356  14383
14357  14357  14383
14358  14358  14383
14359  14359  14390
14360  14360  14386
14361  14361  14391
14362  14362  14391
14363  14363  14391
14364  14364  14381
14365  14365  14380
14366  14366  14391
14367  14367  14391
14368  14368  14391
14369  14369  14386
14370  14370  14386
14371  14371  14386
14372  14372  14386
14373  14373  14386
14374  14374  14393
14375  14375  14393

[14376 rows x 2 columns]

In [45]:
scipy.io.savemat(os.path.join(data_dir,'pc'),{"pc":pc_mtx})

In [42]:
p_lable_data = pd.read_csv(os.path.join(data_dir,'paper_label.txt'),header=None,sep='\t')
p_lable_data.sort_values(0)

        0  1
26     21  2
35    169  2
36    171  1
43    239  1
59    309  1
66    315  0
22    605  2
31    673  0
40    806  2
68    874  3
73    918  2
87    967  3
93    996  0
99   1019  2
2    1041  2
13   1073  2
67   1380  0
86   1475  1
37   1713  2
55   1829  0
64   1868  2
95   2028  2
46   2308  1
65   2390  2
6    2588  1
12   3631  2
76   3989  2
8    4137  2
45   4346  3
92   4572  1
..    ... ..
18   9797  0
57  10030  1
17  10302  3
75  10640  0
97  10742  2
0   10761  3
44  11513  2
49  11532  3
32  11938  2
60  12086  2
61  12091  3
16  12347  2
42  12525  2
25  12563  0
10  12845  1
23  12904  0
28  12945  2
48  13067  2
74  13193  2
11  13358  1
52  13594  2
77  13718  0
83  13747  2
9   13868  0
20  13901  2
21  13914  2
34  13990  0
47  14089  3
85  14274  0
98  14328  3

[100 rows x 2 columns]